# Generated by Django 5.1.5 on 2025-01-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(max_length=255)),
                ('email_address', models.TextField(max_length=255)),
                ('phone_number', models.TextField(max_length=255)),
                ('budget', models.TextField(max_length=255)),
                ('message', models.TextField(max_length=255)),
            ],
        ),
    ]
