# Generated by Django 5.1.5 on 2025-01-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorblend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='budget',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
